### PR TITLE
Better testing for when cross-spawn-async needed

### PR DESCRIPTION
**Pull request by isaacs**
Fix https://github.com/tapjs/foreground-child/issues/5

### CODE REVIEW

**Comment by bcoe** [comment]
@isaacs mind publishing to a @next tag and I'll test on windows? I'll create a corresponding ticket on nyc to add tests for this behavior.

**Comment by isaacs** [comment]
@bcoe done

```
$ npm publish --tag=next
+ foreground-child@1.3.5-beta.0
```

**Comment by bcoe** [comment]
screen shot 2016-01-24 at 11 27 55 am

Works great :+1: want to land this and I'll get a release of nyc out the door?

**Pull request merged**
