### PR TITLE
refactor: use ES2015

### PR DESCRIPTION
**Pull request by demurgos**
# Why

Following tapjs/foreground-child#24, the library requires Node 6. This allows to use ES2015 features to make the code more expressive and easier to maintain.

# What

Replace `var` declarations by `const` or `let`. Use arrow functions. Replace `arguments` slicing with rest arguments. Use `Map` to store the listeners.

### CODE REVIEW

**Review by coreyfarrell — APPROVED** [review]
LGTM @isaacs @bcoe

**Comment by isaacs** [comment]
+1, but this has conflicts with master, please rebase.

**Comment by coreyfarrell** [comment]
@demurgos do you have a chance to work on this?

**Comment by demurgos** [comment]
Thanks for the reminder @coreyfarrell 
I'll rebase the commit and fix the conflicts.

**Comment by demurgos** [comment]
I rebased the PR and fixed the conflicts. The only change was in the `proxySignals` function (extra parameter).

**Comment by demurgos** [comment]
I am looking into the errors: they seem to also be present on `master`.

**Comment by demurgos** [comment]
CI is failing on Node 6 because `tap` dropped support for Node 6. It passes on Node 8. I don't know why it fails on Node 10. It passes locally using Node 10: is the test flaky?

**Pull request merged**
